version: "3.2"

services:
  mysql:
    image: mysql:5.7
    env_file:
      - .env/.env.dev
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql
  app:
    image: app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env/.env.dev
    volumes:
      - .:/app
      - static_data:/app/staticfiles
    depends_on:
      - mysql
    expose:
      - 8000
  migration:
    image: app
    command: python manage.py migrate --noinput
    volumes:
      - .:/app
    depends_on:
      - app
    env_file:
      - .env/.env.dev
  collectstatic:
    image: app
    command: python manage.py collectstatic --noinput
    volumes:
      - .:/app
    depends_on:
      - app
    env_file:
      - .env/.env.dev
  nginx:
    build: ./config/nginx
    ports:
      - 80:80
    depends_on:
      - app

    volumes:
      - ./mysql_data:/var/lib/mysql
#      - ./config/nginx:/etc/nginx/conf.d
      - static_data:/app/staticfiles:ro # ro : read only
volumes:
  mysql_data:
  static_data: