version: "3.2"

services:
  mysql:
    image: mysql:5.7
    environment:
      # overwritten by .env file
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: admin_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    env_file:
      - .env
    ports:
      - 3306:3306
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - mysql
    ports:
      - 8000:8000