version: "3.2"

services:
  mysql:
    image: mysql:5.7
    env_file:
      - env/.env
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql
  app:
    image: app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - env/.env
    volumes:
      - .:/app
    depends_on:
      - mysql
    expose:
      - 8000
  migration:
    image: app
    command: python manage.py migrate --noinput
    volumes:
      - .:/app
    depends_on:
      - app
    env_file:
      - env/.env
  collectstatic:
    image: app
    command: python manage.py collectstatic --noinput
    volumes:
      - .:/app
    depends_on:
      - app
    env_file:
      - env/.env
  nginx:
    build: ./config/nginx
    ports:
#      - 80:80 # upstram is routing to appserver nginx.cong
#      - 80:8000
      - 8000:80
    depends_on:
      - app
volumes:
  mysql_data: