version: "3.2"

services:
  mysql:
    image: mysql:5.7
    env_file:
      - .env
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql
  app:
    image: app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - mysql
      - migration
#      - collectstatic
    ports:
      - 8000:8000
  migration:
    image: app
    command: python manage.py migrate --noinput
    volumes:
      - .:/app
    depends_on:
      - mysql
    env_file:
      - .env
  collectstatic:
    image: app
    command: python manage.py collectstatic --noinput
    volumes:
      - .:/app
    depends_on:
      - app
    env_file:
      - .env
  nginx:
    build: ./config/nginx
    ports:
      - 8000:80
    depends_on:
      - app
volumes:
  mysql_data: