#apiVersion: v1
#kind: Pod
#metadata:
#  name: nginx
#spec:
#  containers:
#    - name: nginx
#      image: nginx:1.17.3
#      ports:
#        - containerPort: 80

#Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  selector:
    matchLabels:
      app: auth-label
  replicas: 2
  template:
    metadata:
      labels:
        app: auth-label
    spec:
      containers:
        - name: auth-app
          image: umeshvjti/auth-service:latest
          ports:
            - containerPort: 80
---
#Service
apiVersion: v1
kind: Service
metadata:
  name: auth-label
spec:
  type: NodePort
  ports:
    - port: 80
  selector:
    app: app-nginx