version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/python:3.7

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Install ENV
          command: |
            PYTHONFAULTHANDLER=1
            DATABASE=sqlite
            sudo apt-get update
            sudo apt-get install python-pip python-dev build-essential
            sudo pip install setuptools --upgrade
            sudo pip install awsebcli --upgrade

      - restore_cache:
          key: dep-{{ .Branch }}-{{ checksum "Pipfile" }}
      - run:
          command: |
            sudo pip install pipenv
            pipenv install --system --ignore-pipfile --dev
      - save_cache:
          key: dep-{{ .Branch }}-{{ checksum "Pipfile" }}
          paths:
            - "venv"

      - run:
          name: Test
          command: python manage.py test
          environment:
              DATABASE: sqlite


      - run:
          name: Build
          command: docker build -t umeshvjti/auth-service:latest .

      - run:
          name: Push
          command: |
            docker login -u$DOCKER_USER -p$DOCKER_PASS
            docker tag umeshvjti/auth-service:latest umeshvjti/auth-service:${CIRCLE_SHA1}
            docker push umeshvjti/auth-service:latest
            docker push umeshvjti/auth-service:${CIRCLE_SHA1}
      - run:
          name: Deploy
          command: |
            eb deploy

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master