# Generated by Django 2.2 on 2020-07-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200715_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country_code',
            field=models.CharField(blank=True, help_text='Country code of the phone number', max_length=3, verbose_name='country code'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, help_text='Include the country code. for the phone number', max_length=15, verbose_name='phone number'),
        ),
    ]
