# Use below encoding to generate encoded data
# echo -n 'admin' | base64
# YWRtaW4=
apiVersion: v1
kind: Secret
metadata:
  name: appsecrets
type: Opaque
data:
  DJANGO_SECRET_KEY: dTV4K2w2bTQAoc2k0Nz1wQWENyNzLSs5cWwqOXVtPSNleUBAXiVtZDR4amNyYihsODE1eXg=
  TWILLIO_AUTH_TOKEN: dTV4K2w2bTQAoc2k0Nz1wQWENyNzLSs5cWwqOXVtPSNleUBAXiVtZDR4amNyYihsODE1eXg=
  TWILLIO_ACCOUNT_SID: dTV4K2w2bTQAoc2k0Nz1wQWENyNzLSs5cWwqOXVtPSNleUBAXiVtZDR4amNyYihsODE1eXg=
  TWILLIO_API_KEY_SID: dTV4K2w2bTQAoc2k0Nz1wQWENyNzLSs5cWwqOXVtPSNleUBAXiVtZDR4amNyYihsODE1eXg=
  TWILLIO_API_KEY_SECRET: dTV4K2w2bTQAoc2k0Nz1wQWENyNzLSs5cWwqOXVtPSNleUBAXiVtZDR4amNyYihsODE1eXg=
  MAILGUN_API_KEY: dTV4K2w2bTQAoc2k0Nz1wQWENyNzLSs5cWwqOXVtPSNleUBAXiVtZDR4amNyYihsODE1eXg=
  EMAIL_HOST_PASSWORD: dTV4K2w2bTQAoc2k0Nz1wQWENyNzLSs5cWwqOXVtPSNleUBAXiVtZDR4amNyYihsODE1eXg=
  POSTGRES_PASSWORD: dTV4K2w2bTQAoc2k0Nz1wQWENyNzLSs5cWwqOXVtPSNleUBAXiVtZDR4amNyYihsODE1eXg=
